spring.application.name=Azure

spring.cloud.azure-directory.enabled=true

spring.cloud.azure-directory.credential.client-id=a24980c7-d61a-48af-a515-e3c44be91c48

spring.cloud.azure-directory.credential.app-id-uri=api://a24980c7-d61a-48af-a515-e3c44be91c48